# Config for Travis CI, tests powered by DepHell.
# https://travis-ci.org/
# https://github.com/dephell/dephell

language: python
dist: xenial

# do not run Travis for PR's twice (as for push and as for PR)
branches:
  only:
    - master

before_install:
  # show a little bit more information about environment
  - sudo apt-get install -y tree
  - env
  - tree
  # install DepHell
  # https://github.com/travis-ci/travis-ci/issues/8589
  - curl -L dephell.org/install | /opt/python/3.7/bin/python
  - dephell inspect self
install:
  - dephell venv create --env=$ENV --python="/opt/python/$TRAVIS_PYTHON_VERSION/bin/python"
  - dephell deps install --env=$ENV
script:
  - dephell venv run --env=$ENV

matrix:
  include:

    - python: "3.6.7"
      env: ENV=pytest
    - python: "3.7"
      env: ENV=pytest
    - python: "3.8"
      env: ENV=pytest
    - python: "pypy3"
      env: ENV=pytest

    - python: "3.7"
      env: ENV=flake8
